apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsgenie-heartbeat.fullname" . }}
  labels:
    {{- include "opsgenie-heartbeat.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opsgenie-heartbeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opsgenie-heartbeat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opsgenie-heartbeat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: OPSGENIE_APIKEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingSecret }}
                key: "apikey"
          - name: OPSGENIE_HEARTBEAT_NAME
            value: {{ .Values.heartbeatName }}
          - name: OPSGENIE_LIVE_REPLY
            value: {{ .Values.liveReply | default "1h" | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            periodSeconds: 60
            httpGet:
              path: /heartbeat
              port: http
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
