{{- define "pipeline.buildpack" -}}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .pipeline.name }}
spec:
  description: |-
    {{- .pipeline.description | default (printf "Pipeline will only build the image utilizing %s task and then send notification via slack. The deployment is done via argocd" (.pipeline.buildTaskName)) | nindent 4}}

  params:
    - name: application
      type: string
      description: name of the argocd application we're going to deploy/sync

    - name: sha
      type: string
      description: sha commit ID of the image deployed in cluster

    - name: head_commit
      type: string
      description: full SHA commit ID

    - name: head_commit_message
      type: string
      description: description of the commit (by developer)

    - name: pusher_name
      type: string
      description: author name

    - name: pusher_email
      type: string
      description: author email

    - name: pusher_avatar
      type: string
      description: author avatar

    - name: pusher_url
      type: string
      description: author link to profile

    - name: repository_url
      type: string    
      description: git repository https url 

    - name: branch
      type: string
      description: git branch

    - name: buildpack_builder_image
      type: string
      description: the image on which builds will run (must include lifecycle and compatible buildpacks).

    - name: buildpack_runner_image
      type: string
      description: reference to a run image to use

    - name: docker_registry
      type: string
      description: private docker registry address

    - name: docker_registry_repository
      type: string    
      description: private docker registry repository address

    - name: source_subpath
      type: string
      description: a subpath within the `source` input where the source to build is located.
      default: ""

    - name: kubernetes_repository_kustomize_path
      type: string
      description: overlay path for kustomize call

    - name: kubernetes_branch
      type: string
      default: main
      description: git branch for kustomize managed git repo

    - name: platform_dir
      type: string
      description: name of the platform directory. for buildpack /cnb/lifecycle/creator
      default: "platform"

    - name: environment
      type: string
      description: environment name of the app being built, i.e. dev/staging/prod

  workspaces:
    - name: source

  resources:
    - name: app
      type: git
    - name: kubernetes-repo
      type: git
    - name: image
      type: image

  tasks:
    - name: buildpack-set-env-vars
      taskRef:
        name: buildpack-set-env-vars
      resources:
        inputs:
          - name: app
            resource: app
      params:
        - name: application
          value: "$(params.application)"
        - name: environment
          value: "$(params.environment)"
        - name: platform_dir
          value: "$(params.platform_dir)"
      workspaces:
        - name: source
          workspace: source

    - name: {{ .pipeline.buildTaskName }}
      taskRef:
        name: {{ .pipeline.buildTaskName }}
      resources:
          inputs:
            - name: app
              resource: app
          outputs:
              - name: image
                resource: image
      params:
        - name: application
          value: "$(params.application)"
        - name: builder_image
          value: "$(params.buildpack_builder_image)"
        - name: run_image
          value: "$(params.buildpack_runner_image)"
        - name: docker_registry
          value: $(params.docker_registry)
        - name: cache
          value: $(params.application)-buildpacks-cache        
        - name: source_subpath
          value: "$(params.source_subpath)"
        - name: platform_dir
          value: "$(params.platform_dir)"
        - name: environment
          value: "$(params.environment)"
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - set-env-vars

    - name: kustomize
      taskRef:
        name: kustomize
      resources:
        inputs:
          - name: kubernetes-repo
            resource: kubernetes-repo
      params:
        - name: application
          value: "$(params.application)"        
        - name: image
          value: "$(params.docker_registry_repository):$(params.environment)-$(params.sha)"
        - name: kustomize_overlay_path
          value: "$(params.kubernetes_repository_kustomize_path)"
        - name: kubernetes_branch
          value: "$(params.kubernetes_branch)"
        - name: environment
          value: "$(params.environment)"
      runAfter:
        - {{ .pipeline.buildTaskName }}

    - name: argocd-deploy
      taskRef:
        name: argocd-deploy
      params:
        - name : application
          value: "$(params.application)"        
      runAfter: 
        - kustomize

  finally:
    - name: slack-notification
      taskRef:
        name: slack-notification
      params:
        - name: application
          value: "$(params.application)"
        - name: sha
          value: "$(params.sha)"
        - name: head_commit
          value: "$(params.head_commit)"
        - name: head_commit_message
          value: "$(params.head_commit_message)"
        - name: pusher_name
          value: "$(params.pusher_name)"
        - name: pusher_email
          value: "$(params.pusher_email)"
        - name: pusher_avatar
          value: "$(params.pusher_avatar)"
        - name: pusher_url
          value: "$(params.pusher_url)"
        - name: repository_url
          value: "$(params.repository_url)"
        - name: branch
          value: "$(params.branch)"
        - name: environment
          value: "$(params.environment)"
        - name: status
          value: "$(tasks.argocd-deploy.status)"
---
{{- end }}
