{{- range $pipeline := .Values.buildpacks.generate }}
{{$data := dict "pipeline" $pipeline }}
{{ if and $.Values.buildpacks.enabled $pipeline.enabled }}
{{ include "pipeline.buildpack" $data }}
{{ end }}
{{- end}}
