{{- if and .Values.engine.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton.serviceAccountName" . }}
  namespace: tekton-pipelines
  labels:
    {{- include "tekton.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton.serviceAccountName" . }}
  namespace: {{ include "tekton.eventlistenerNamespace" . }}
  labels:
    {{- include "tekton.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
