{{ if .Values.eventlistener.create }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ include "tekton-apps.eventlistenerName" .Values.eventlistener.suffix }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}
  {{- if .Values.nodeSelector }}
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            nodeSelector:
              {{- toYaml .Values.nodeSelector | nindent 14 }}
  {{- end }}
  {{- if .Values.eventlistener.labelSelector }}
  labelSelector:
    matchLabels:
      {{- .Values.eventlistener.labelSelector | toYaml | nindent 6 }}
  {{- end }}

{{- end }}  {{/* if apps */}}
