{{ if .Values.apps }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: build-pipeline-event-listener
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}
  triggers:
  {{- range $project := .Values.apps }}
  {{- if $project.enabled }}
  # ========================================================================
  # {{ $project.project | upper }} PROJECT
  {{- range $component := $project.components }}

  {{- /* initialize `argocd` variable with either `$component.argocd` dict if it exists or with empty dict */}}
  {{ $argocd := ternary $component.argocd dict (hasKey $component "argocd") -}}

  {{- /* initialize `wordpress` variable with either `$argocd.wordpress` dict if it exists or with empty dict */}}
  {{ $wordpress := ternary $argocd.wordpress dict (hasKey $argocd "wordpress") -}}

  {{- /* if wordpress.ci is set to `true` or `nil` - it means that project uses wordpress deployment, otherwise - not */}}
  {{ if ternary $wordpress.ci "true" (hasKey $wordpress "ci") }}

  # ========================================================================
  # 🐤 {{ $project.project | upper }}/{{ $component.name | upper }} COMPONENT
  # ========================================================================

  {{- /* initialize `gitBranchPrefixes` variable with either `$component.eventlistener.gitWebhookBranches`
  list if it exists or `$.Values.gitBranchPrefixes` otherwise */}}
  {{ $gitBranchPrefixes := ternary $component.eventlistener.gitWebhookBranches $.Values.gitBranchPrefixes (hasKey $component.eventlistener "gitWebhookBranches") -}}

  {{- $data := dict "project"           $project
                    "component"         $component
                    "environment"       $.Values.environment
                    "eventlistener"     $.Values.eventlistener
                    "gitBranchPrefixes" $gitBranchPrefixes }}
  {{- include "tekton-apps.eventlistener.trigger" $data | nindent 4 }}
  {{- end }} # range component
  {{- end }} # if project.enabled
  {{- end }} # if $wordpress.ci
  {{- end }} # range
  {{- end }} # if apps
