{{ if .Values.apps }}

# this is default sa under which we run our EventListener
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}

{{- end }} {{- /* if apps */}}
