{{ if .Values.apps }}
{{- range $project := .Values.apps }}

{{- if $project.enabled }}
{{- range $component := $project.components }}
{{- $data := dict "project"           $project
                  "component"         $component
                  "environment"       $.Values.environment }}

# ========================================================================
# 🌱 {{ $project.project | upper }}/{{ $component.name | upper }} COMPONENT TRIGGER BINDING
# ========================================================================
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name:  {{ include "tekton-apps.resourceName" $data }}-env
  namespace: {{ $.Release.Namespace }}
spec:
  params:
  - name: application
    value: {{ include "tekton-apps.resourceName" $data }}
  - name: environment
    value: {{ $.Values.environment }}
  {{- if $.Values.defaultRegistry }}
  - name: docker_registry
    value: {{ $.Values.defaultRegistry }}
  {{- end }}
  {{- toYaml $component.triggerBinding | nindent 2 }}
  - name: kubernetes_repository_ssh_url
    value: {{ $project.kubernetesRepository.url }}
  # defaults
  {{- include "tekton-apps.get-triggerbinding-value-or-default" (dict "triggerBinding" $component.triggerBinding "name" "kubernetes_branch" "default" "main" ) | nindent 2 }}
  {{- include "tekton-apps.get-triggerbinding-value-or-default" (dict "triggerBinding" $component.triggerBinding "name" "kubernetes_repository_kustomize_path" "default" (printf "apps/%s/manifests/%s" $component.name $.Values.environment) ) | nindent 2 }}
  {{- include "tekton-apps.get-triggerbinding-value-or-default" (dict "triggerBinding" $component.triggerBinding "name" "source_subpath" "default" "." ) | nindent 2 }}
---

{{- end }} # range component
{{- end }} # if project.enabled
{{- end }} # range
{{- end }} # if apps
