{{ if and .Values.kaniko.enabled }}
{{ $data := dict "extraSteps" .Values.kaniko.extraPostDeployTaskSteps
                 "namespace"  $.Release.Namespace
                 "namePrefix" "kaniko" }}
{{ include "task.postDeploy" $data }}
{{ end }}
