{{ if .Values.rbac.developers.mysql }}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: saritasa-developers-role
 namespace: mysql
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward", "pods/exec"]
    verbs: ["create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: saritasa:developers
  namespace: mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: saritasa-developers-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: saritasa:sso:developers

{{ end }}
