{{ if .Values.rbac.client.postgres }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ .Values.rbac.client.name }}-readonly-role
 namespace: postgres
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward", "pods/exec"]
    verbs: ["create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.client.name }}:developers
  namespace: postgres
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.client.name }}-readonly-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ .Values.rbac.client.name }}:view

{{ end }}
