apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-deploy
  namespace: {{ .Release.Namespace }}

spec:
  description: >-
    The task parses project.toml file and stores its environment variables
    values to platform dir for further processing by buildpack task.

  params:
    - name: application
      type: string
      description: name of the argocd application we're going to deploy/sync

  stepTemplate:
    envFrom:
      - configMapRef:
          name: $(params.application)-build-pipeline-config # project specific values
      - secretRef:
          name: $(params.application)-argocd-secret  # used for authentication (username/password or auth token)
  steps:
    - name: deploy
      image: cfmanteiga/alpine-bash-curl-jq
      imagePullPolicy: {{ .Values.imagePullPolicy }}
      script: |
        #!/usr/bin/env bash
        set +x
        curl --silent -o /usr/local/bin/argocd {{ .Values.images.argocd_cli }}

        # connect to private service
        # instead of connecting through a public ingress
        echo "login to argocd"
        yes | argocd login \
          --insecure argo-cd-argocd-server.argo-cd \
          --grpc-web \
          --grpc-web-root-path $ARGOCD_ROOT_PATH \
          --username $ARGOCD_USERNAME \
          --password $ARGOCD_PASSWORD \
          --http-retry-max 3

        echo "app sync $(params.application)"
        argocd app sync $(params.application)

        argocd app wait $(params.application) \
          --health=true \
          --operation=true

        synced=`argocd app get $(params.application) -o json | jq -r '.status.sync.status' | awk '{print tolower($1)}'`
        healthy=`argocd app get $(params.application) -o json | jq -r '.status.health.status' | awk '{print tolower($1)}'`

        [[ "$synced" == "synced" ]] && [[ "$healthy" == "healthy" ]] && echo "Sync completed succcessfully. App is healthy!" || (echo "Sync failed" && exit 1)
