apiVersion: v2
name: saritasa-tekton-apps
description: A Helm chart for tekton apps (rbac, eventlistener)

type: application

# This is the version number of the tekton engine application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.28.2"
triggersVersions: "v0.16.0"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2


maintainers:
  - url: https://www.saritasa.com/
    name: Saritasa