apiVersion: v2
name: maintenance-page

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.3

maintainers:
  - url: https://www.sea12tech.com/
    name: Saritasa
    email: nospam@sea12tech.com

description: |
  A Helm chart for Kubernetes to display a simple maintenance page.
  By default it displays the following content:
  [https://codepen.io/Neil-Mayers/pen/XJJNqNv](https://codepen.io/Neil-Mayers/pen/XJJNqNv)

  You can adjust the look by setting up the following values in the values.yaml file:


  ```yaml
  message:
    backgroundColor: "#d6433b"
    textColor: "#fff"
    title: "Site Maintenance"
    header: "We&rsquo;ll be back soon!"
    body: |
      <p>Sorry for the inconvenience. We&rsquo;re performing some maintenance at the moment. We&rsquo;ll be back up shortly!</p>
    footer: |
      <p>&mdash; The DevOps Team</p>
  ```

  or by supplying an entire HTML for the maintenance page via

  ```yaml
  html: |
    hello, the maintenance page HTML + CSS code is here
  ```