{{- range $pipeline := .Values.buildpacks.generate }}
{{$data := dict "pipeline"        $pipeline 
                "namespace"       $.Release.Namespace
                "cnbPlatformAPI"  $.Values.buildpacks.cnbPlatformAPI 
                "images"          $.Values.images 
                "imagePullPolicy" $.Values.imagePullPolicy }}
{{ if and $.Values.buildpacks.enabled $pipeline.enabled }}
{{ include "task.buildpack" $data }}
{{ end }}
{{- end}}
