{{- range $pipeline := $.Values.buildpacks.generate }}
{{ $data := dict "extraSteps" $pipeline.extraPostDeployTaskSteps
                 "namespace"  $.Release.Namespace
                 "namePrefix" $pipeline.name }}
{{ if and (and $.Values.buildpacks.enabled $pipeline.enabled) }}
{{ include "task.postDeploy" $data }}
{{ end }}
{{- end}}
